### ISSUE TITLE
GottaGoFast seems to crash on game boot.

### ISSUE THREAD

**Issue by Dragonruler6008** [kinsi55/CS_BeatSaber_GottaGoFast#1]
**Describe the bug**
 The crash handler pops up when I put GottaGoFast in the plugins folder and start the game.

**To Reproduce**
1. Install core (all force checked + Scoresaber) mods from Mod Assistant
3.Put Gottagofast in the plugin directory
4.Lauch game.
5.Crash handler appears and game crashes.

**Game Version**
1.13.2
**Nvidia driver version**
461.09

**List of other Mods**
![image](https://user-images.githubusercontent.com/73806560/105568540-68365200-5cf7-11eb-9476-f3e4bf6fe3b3.png)

**Game boot log for debugging from Mod assistant**
https://p.teknik.io/ba2Ac

(Maybe I did something stupid when updating my mods so if so let me know if this is completely wrong. Hope I help instead of hinder :P) (Thanks for a great mod I really do love it!)

**Comment by kinsi55** [comment]
I've had various people try out GGF on the latest version and neither of them had any issues, you do seem to get a weird error logged at the very end of your log tho which says something about leaderboard - Have you tried removing ScoreSaber? Seems like maybe one your your configuration files is messed up.

What you could try is renaming your UserData folder to something else (As a backup) which would casue it to get completely re-generated

**Comment by Dragonruler6008** [comment]
After I tried the suggested answer BeatSaber continued to crash. I then just decided to reinstall BeatSaber and this seems to have worked. I guess somewhere in the BeatSaber code something got put where it shouldn't have. Thanks for your quick reply!

**Comment by kinsi55** [comment]
You're welcome, glad you figured it out :)
