### ISSUE TITLE
Any reason this is not a default over Mod Assistant?

### ISSUE THREAD

**Issue by xJon** [kinsi55/CS_BeatSaber_GottaGoFast#2]
Great mod! and hard to get used to not having it. I just figured more people would know about it if it was included in Mod Assistant.

**Comment by kinsi55** [comment]
Nowadays, not necessarily. There used to be some issues that some people had with it but nowadays those seem to be ironed out.

My only real reason for not having it in ModAssistant would be a dumb one - I dont want people to think that basegame load times are as good as they are with this mod, but I should probably just submit it.

**Comment by kinsi55** [comment]
I've submitted it now for ModAssistant (it'll be a bit before its approved tho)

**Comment by xJon** [comment]
I can't find it again, is it not marked as 1.28 compatible?

**Comment by kinsi55** [comment]
It ended up never being approved in time for the 1.27 (?) release it seems and thus it didnt carry on. Its still compatible, I'll re-submit it maybe this time around it will get approved :D

**Comment by xJon** [comment]
Not listed (still) for `1.29.1` lol
