### ISSUE TITLE
UI crash with _settings options of Chroma and GottaGoFast

### ISSUE THREAD

**Issue by Elecast2** [kinsi55/CS_BeatSaber_GottaGoFast#3]
**Describe the bug**
The UI crashes when using _settings options and gottaGoFast. The _settings options allow for temporary enabling options that the map needs for the chroma to work and then disable them when the map is closed or you lose. When I use gottaGoFast and open a map with the _settings options, the UI crashes when I finish or lose the map.

The _settings option is located in the Info.dat file of the map. Example:
```
"_settings": {
	"_playerOptions": {
		"_environmentEffectsFilterDefaultPreset": "AllEffects",
		"_environmentEffectsFilterExpertPlusPreset": "AllEffects"
	},
	"_environments": {
		"_overrideEnvironments": false
	},
	"_chroma": {
		"_disableChromaEvents": false,
		"_disableEnvironmentEnhancements": false,
		"_disableNoteColoring": false
	}
}
```

**To Reproduce**
      1. Open a map with the _settings options of chroma, chroma must be disabled and GottaGoFast enabled (Examples: https://beatsaver.com/maps/31f75 https://beatsaver.com/maps/2b874)
      2. Click on Accept the options
      3. Finish or lose the map (sometimes it happens in the 2nd or 3rd try)
      4. UI stop responding

**Screenshots / Videos**
![image](https://github.com/kinsi55/CS_BeatSaber_GottaGoFast/assets/23460760/3ed5d17b-b42d-4b92-ba35-7fddc426c534)

**Game Version**
1.29.1

**List of other Mods**
```
BeatLeader
BeatSaberPlus
BeatSaberPlus_Chat
BeatSaberPlus_ChatEmoteRain
BeatSaberPlus_ChatIntegrations
BeatSaberPlus_ChatRequest
BeatSaberPlus_GameTweaker
BeatSaberPlus_MenuMusic
BeatSaberPlus_Multiplayer
BeatSaberPlus_NoteTweaker
BeatSaberPlus_SongChartVisualizer
BeatSaberPlus_SongOverlay
BeatSaverDownloader
BeatSaverUpdater
BeatSaverVoting
BeatSaviorData
BetterSongList
BetterSongSearch
BSML
BS_Utils
Camera2
Chroma
ControllerTweaks
Counters+
CustomJSONData
CustomNotes
EasyOffset
FastFail
FCPercentage
GottaGoFast
Heck
HitScoreVisualizer
HitsoundTweaks
IForgor
IntroSkip
JDFixer
LeaderboardCore
MappingExtensions
MorePrecisePlayerHeight
NoodleExtensions
OverrideEnvironmentFix
PlaylistManager
SaberFactory
ScorePercentage
ScoreSaber
SearchFixes
SiraUtil
SmartSongSuggest
SongCore
SongDescriptionButItWorks
SoundReplacer
TakeMeToResults
Tweaks55
WhyIsThereNoLeaderboard
wipbot
```

**Comment by kinsi55** [comment]
Ty for the report, I'll try to look into it at some point, altho this would likely be something that has to be fixed on Chromas end

**Comment by Dereknalox123** [comment]
Some extra Info:

1.- You don't need to press "Accept" necessarily, if you press "Decline" this will happen anyway.
2.- Even if GottaGoFast is not Enabled in-game the UI problem will keep happening.
3.- If you play a map that has a prompt and you already have all the settings that the prompt would ask you to enable, the prompt will not appear and the map will work fine almost always. However, if you play a Chroma map after that and the prompt appears, whether you press “Decline” or “Accept”, the UI problem will not happen anymore and it will work normally.

**Comment by kinsi55** [comment]
Can you try and see if the bug still exists if you remove ScoreSaber?

**Comment by kinsi55** [comment]
This is an issue that spreads over GGF + SS + Heck - The fix would be applied in Heck (Already has been), just isnt released yet.
